config/routes.rb
Refinery::Application.routes.draw do
  resources :courses, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :courses, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :parts, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :parts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_parts, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_parts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :part_prerequisites, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :part_prerequisites, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :venues, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :venues, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :attendees, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :attendees, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_events, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_events, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_event_attendees, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_event_attendees, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :instructors, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :instructors, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_event_instructors, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_event_instructors, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :skills, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :skills, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :instructor_skills, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :instructor_skills, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/course_event_attendee.rb
class CourseEventAttendee < ActiveRecord::Base
  belongs_to :course_event
  belongs_to :attendee

  def title
    %[#{attendee.full_name} is enrolled in #{course_event.title}]
  end
  
end

app/controllers/admin/course_event_attendees_controller.rb
module Admin
  class CourseEventAttendeesController < Admin::BaseController

    crudify :course_event_attendee, :xhr_paging => true

  end
end

app/controllers/course_event_attendees_controller.rb
class CourseEventAttendeesController < ApplicationController

  before_filter :find_all_course_event_attendees
  before_filter :find_page

  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @course_event_attendee in the line below:
    present(@page)
  end

  def show
    @course_event_attendee = CourseEventAttendee.find(params[:id])

    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @course_event_attendee in the line below:
    present(@page)
  end

protected

  def find_all_course_event_attendees
    @course_event_attendees = CourseEventAttendee.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/course_event_attendees").first
  end

end

app/views/admin/course_event_attendees/_actions.html.erb
<ul>
  <% if Admin::CourseEventAttendeesController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_course_event_attendees_url
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_course_event_attendee_url,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::CourseEventAttendeesController.sortable? and CourseEventAttendee.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Course Event Attendees"),
                 admin_course_event_attendees_url,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Course Event Attendees"),
                 admin_course_event_attendees_url,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/course_event_attendees/_course_event_attendee.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(course_event_attendee) -%>">
  <span class='title'>
    <%= course_event_attendee.title %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), course_event_attendee_url(course_event_attendee),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_course_event_attendee_path(course_event_attendee),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_course_event_attendee_path(course_event_attendee),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => course_event_attendee.title),
        :method => :delete %>
  </span>
</li>

app/views/admin/course_event_attendees/_course_event_attendees.html.erb
<%= will_paginate @course_event_attendees %>
<%= render :partial => "sortable_list" %>

app/views/admin/course_event_attendees/_form.html.erb
<%= form_for [:admin, @course_event_attendee] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @course_event_attendee,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :course_event_id -%>
    <%= f.text_field :course_event_id, :class => 'larger widest' -%>
  </div>
  
  <div class='field'>
    <%= f.label :attendee_id -%>
    <%= f.text_field :attendee_id -%>
  </div>
  
  <div class='field'>
    <%= f.label :position -%>
    <%= f.text_field :position -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.course_event_attendees.course_event_attendee'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete')
              } %>
<% end -%>

app/views/admin/course_event_attendees/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @course_event_attendees.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'course_event_attendees' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/course_event_attendees/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'course_event_attendee', :collection => @course_event_attendees %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/course_event_attendees/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/course_event_attendees/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::CourseEventAttendeesController.sortable? and CourseEventAttendee.count > 1 %>

app/views/admin/course_event_attendees/new.html.erb
<%= render :partial => "form" %>