config/routes.rb
Refinery::Application.routes.draw do
  resources :courses, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :courses, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :parts, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :parts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_parts, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_parts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :part_prerequisites, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :part_prerequisites, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :venues, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :venues, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :attendees, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :attendees, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_events, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_events, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_event_attendees, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_event_attendees, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :instructors, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :instructors, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_event_instructors, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_event_instructors, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :skills, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :skills, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :instructor_skills, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :instructor_skills, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  acts_as_taggable
  acts_as_commentable
  acts_as_indexed :fields => [:name]
  
  has_many :instructor_skills
  has_many :instructors, :through => :instructor_skills

  validates :name, :presence => true, :uniqueness => true
  
end

app/controllers/admin/skills_controller.rb
module Admin
  class SkillsController < Admin::BaseController

    crudify :skill,
            :title_attribute => 'name', :xhr_paging => true

  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController

  before_filter :find_all_skills
  before_filter :find_page

  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @skill in the line below:
    present(@page)
  end

  def show
    @skill = Skill.find(params[:id])

    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @skill in the line below:
    present(@page)
  end

protected

  def find_all_skills
    @skills = Skill.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/skills").first
  end

end

app/views/admin/skills/_actions.html.erb
<ul>
  <% if Admin::SkillsController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_skills_url
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_skill_url,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::SkillsController.sortable? and Skill.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Skills"),
                 admin_skills_url,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Skills"),
                 admin_skills_url,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/skills/_form.html.erb
<%= form_for [:admin, @skill] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @skill,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest' -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.skills.skill'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @skill.name)
              } %>
<% end -%>

app/views/admin/skills/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @skills.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'skills' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/skills/_skill.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(skill) -%>">
  <span class='title'>
    <%= skill.name %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), skill_url(skill),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_skill_path(skill),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_skill_path(skill),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => skill.name),
        :method => :delete %>
  </span>
</li>

app/views/admin/skills/_skills.html.erb
<%= will_paginate @skills %>
<%= render :partial => "sortable_list" %>

app/views/admin/skills/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'skill', :collection => @skills %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/skills/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/skills/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::SkillsController.sortable? and Skill.count > 1 %>

app/views/admin/skills/new.html.erb
<%= render :partial => "form" %>