config/routes.rb
Refinery::Application.routes.draw do
  resources :courses, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :courses, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :parts, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :parts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_parts, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_parts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :part_prerequisites, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :part_prerequisites, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :venues, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :venues, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :attendees, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :attendees, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_events, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_events, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_event_attendees, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_event_attendees, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :instructors, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :instructors, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_event_instructors, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_event_instructors, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :skills, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :skills, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :instructor_skills, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :instructor_skills, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  include ActsAsAddressable
  
  acts_as_addressable
  acts_as_taggable
  ajaxful_rater
  acts_as_indexed :fields => [:first_name, :last_name, :email, :short_bio, :bio, :blog_url, :blog_rss_feed, :feed_type, :dc_creator_tag, :twitter_id, :street_address, :apt_suite_other, :city, :region, :postal_code, :country, :country_code, :phone_number, :gender, :website]

  validates :first_name, :presence => true, :uniqueness => true
  
  has_many :course_event_intructors
  has_many :course_events, :through => :course_event_intructors
  has_many :instructor_skills
  has_many :skills, :through => :instructor_skills
  
  def full_name
    %[#{first_name} #{last_name}]
  end
  
  def add_skill(skill_name, rate)
    skill = Skill.find_or_create_by_name(skill_name)
    instructor_skill = InstructorSkill.create(:instructor => self, :skill => skill)
    attendee = Attendee.where(:email => "guestuser@nowhere.com").first;
    instructor_skill.rate(rate, attendee)
  end
end

app/controllers/admin/instructors_controller.rb
module Admin
  class InstructorsController < Admin::BaseController

    crudify :instructor,
            :title_attribute => 'first_name', :xhr_paging => true

  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

  before_filter :find_all_instructors
  before_filter :find_page

  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @instructor in the line below:
    present(@page)
  end

  def show
    @instructor = Instructor.find(params[:id])

    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @instructor in the line below:
    present(@page)
  end

protected

  def find_all_instructors
    @instructors = Instructor.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/instructors").first
  end

end

app/views/admin/instructors/_actions.html.erb
<ul>
  <% if Admin::InstructorsController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_instructors_url
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_instructor_url,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::InstructorsController.sortable? and Instructor.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Instructors"),
                 admin_instructors_url,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Instructors"),
                 admin_instructors_url,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/instructors/_form.html.erb
<%= form_for [:admin, @instructor] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @instructor,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :first_name -%>
    <%= f.text_field :first_name, :class => 'larger widest' -%>
  </div>
  
  <div class='field'>
    <%= f.label :last_name -%>
    <%= f.text_field :last_name -%>
  </div>
  
  <div class='field'>
    <%= f.label :email -%>
    <%= f.text_field :email -%>
  </div>
  
  <div class='field'>
    <%= f.label :short_bio -%>
    <%= f.text_field :short_bio -%>
  </div>
  
  <div class='field'>
    <div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
      <ul id='page_parts'>
        <% [:bio].each_with_index do |part, part_index| %>
          <li class='ui-state-default<%= ' ui-state-active' if part_index == 0 %>'>
            <%= link_to part.to_s.titleize, "##{part}" %>
          </li>
        <% end %>
      </ul>

      <div id='page_part_editors'>
        <% [:bio].each do |part| %>
          <div class='page_part' id='<%= part %>'>
            <%= f.text_area part, :rows => 20, :class => 'wymeditor widest' -%>
          </div>
        <% end %>
      </div>
    </div>
  
  <div class='field'>
    <%= f.label :blog_url -%>
    <%= f.text_field :blog_url -%>
  </div>
  
  <div class='field'>
    <%= f.label :blog_rss_feed -%>
    <%= f.text_field :blog_rss_feed -%>
  </div>
  
  <div class='field'>
    <%= f.label :feed_type -%>
    <%= f.text_field :feed_type -%>
  </div>
  
  <div class='field'>
    <%= f.label :blog_enabled -%>
    <%= f.check_box :blog_enabled -%>
  </div>
  
  <div class='field'>
    <%= f.label :dc_creator_tag -%>
    <%= f.text_field :dc_creator_tag -%>
  </div>
  
  <div class='field'>
    <%= f.label :twitter_id -%>
    <%= f.text_field :twitter_id -%>
  </div>
  
  <div class='field'>
    <%= f.label :twitter_enabled -%>
    <%= f.check_box :twitter_enabled -%>
  </div>
  
  <div class='field'>
    <%= f.label :street_address -%>
    <%= f.text_field :street_address -%>
  </div>
  
  <div class='field'>
    <%= f.label :apt_suite_other -%>
    <%= f.text_field :apt_suite_other -%>
  </div>
  
  <div class='field'>
    <%= f.label :city -%>
    <%= f.text_field :city -%>
  </div>
  
  <div class='field'>
    <%= f.label :region -%>
    <%= f.text_field :region -%>
  </div>
  
  <div class='field'>
    <%= f.label :postal_code -%>
    <%= f.text_field :postal_code -%>
  </div>
  
  <div class='field'>
    <%= f.label :country -%>
    <%= f.text_field :country -%>
  </div>
  
  <div class='field'>
    <%= f.label :country_code -%>
    <%= f.text_field :country_code -%>
  </div>
  
  <div class='field'>
    <%= f.label :phone_number -%>
    <%= f.text_field :phone_number -%>
  </div>
  
  <div class='field'>
    <%= f.label :gender -%>
    <%= f.text_field :gender -%>
  </div>
  
  <div class='field'>
    <%= f.label :website -%>
    <%= f.text_field :website -%>
  </div>
  
  <div class='field'>
    <%= f.label :latitude -%>
    <%= f.text_field :latitude -%>
  </div>
  
  <div class='field'>
    <%= f.label :longitude -%>
    <%= f.text_field :longitude -%>
  </div>
  
  <div class='field'>
    <%= f.label :email_opt_in -%>
    <%= f.check_box :email_opt_in -%>
  </div>
  
  <div class='field'>
    <%= f.label :newsletter_opt_in -%>
    <%= f.check_box :newsletter_opt_in -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.instructors.instructor'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @instructor.first_name)
              } %>
<% end -%>
<% content_for :javascripts do %>
  <script>
    $(document).ready(function(){
      page_options.init(false, '', '');
    });
  </script>
<% end %>

app/views/admin/instructors/_instructor.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(instructor) -%>">
  <span class='title'>
    <%= instructor.first_name %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), instructor_url(instructor),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_instructor_path(instructor),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_instructor_path(instructor),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => instructor.first_name),
        :method => :delete %>
  </span>
</li>

app/views/admin/instructors/_instructors.html.erb
<%= will_paginate @instructors %>
<%= render :partial => "sortable_list" %>

app/views/admin/instructors/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @instructors.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'instructors' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/instructors/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'instructor', :collection => @instructors %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/instructors/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/instructors/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::InstructorsController.sortable? and Instructor.count > 1 %>

app/views/admin/instructors/new.html.erb
<%= render :partial => "form" %>