config/routes.rb
Refinery::Application.routes.draw do
  resources :courses, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :courses, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :parts, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :parts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_parts, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_parts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :part_prerequisites, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :part_prerequisites, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :venues, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :venues, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :attendees, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :attendees, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_events, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_events, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_event_attendees, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_event_attendees, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :instructors, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :instructors, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :course_event_instructors, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :course_event_instructors, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :skills, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :skills, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :instructor_skills, :only => [:index, :show]

  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :instructor_skills, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  include ActsAsAddressable
  
  acts_as_addressable
  ajaxful_rater
  acts_as_indexed :fields => [:first_name, :last_name, :email, :street_address, :apt_suite_other, :city, :region, :postal_code, :country, :country_code, :phone_number, :company, :gender, :website]

  validates :first_name, :presence => true, :uniqueness => true
  
  has_many :course_event_attendees
  has_many :course_events, :through => :course_event_attendees
  
  def full_name
    %[#{first_name} #{last_name}]
  end
  
end

app/controllers/admin/attendees_controller.rb
module Admin
  class AttendeesController < Admin::BaseController

    crudify :attendee,
            :title_attribute => 'first_name', :xhr_paging => true

  end
end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController

  before_filter :find_all_attendees
  before_filter :find_page

  def index
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @attendee in the line below:
    present(@page)
  end

  def show
    @attendee = Attendee.find(params[:id])

    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @attendee in the line below:
    present(@page)
  end

protected

  def find_all_attendees
    @attendees = Attendee.order('position ASC')
  end

  def find_page
    @page = Page.where(:link_url => "/attendees").first
  end

end

app/views/admin/attendees/_actions.html.erb
<ul>
  <% if Admin::AttendeesController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_attendees_url
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_attendee_url,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::AttendeesController.sortable? and Attendee.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Attendees"),
                 admin_attendees_url,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Attendees"),
                 admin_attendees_url,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/attendees/_attendee.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(attendee) -%>">
  <span class='title'>
    <%= attendee.first_name %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), attendee_url(attendee),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_attendee_path(attendee),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_attendee_path(attendee),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => attendee.first_name),
        :method => :delete %>
  </span>
</li>

app/views/admin/attendees/_attendees.html.erb
<%= will_paginate @attendees %>
<%= render :partial => "sortable_list" %>

app/views/admin/attendees/_form.html.erb
<%= form_for [:admin, @attendee] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @attendee,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :first_name -%>
    <%= f.text_field :first_name, :class => 'larger widest' -%>
  </div>
  
  <div class='field'>
    <%= f.label :last_name -%>
    <%= f.text_field :last_name -%>
  </div>
  
  <div class='field'>
    <%= f.label :email -%>
    <%= f.text_field :email -%>
  </div>
  
  <div class='field'>
    <%= f.label :street_address -%>
    <%= f.text_field :street_address -%>
  </div>
  
  <div class='field'>
    <%= f.label :apt_suite_other -%>
    <%= f.text_field :apt_suite_other -%>
  </div>
  
  <div class='field'>
    <%= f.label :city -%>
    <%= f.text_field :city -%>
  </div>
  
  <div class='field'>
    <%= f.label :region -%>
    <%= f.text_field :region -%>
  </div>
  
  <div class='field'>
    <%= f.label :postal_code -%>
    <%= f.text_field :postal_code -%>
  </div>
  
  <div class='field'>
    <%= f.label :country -%>
    <%= f.text_field :country -%>
  </div>
  
  <div class='field'>
    <%= f.label :country_code -%>
    <%= f.text_field :country_code -%>
  </div>
  
  <div class='field'>
    <%= f.label :phone_number -%>
    <%= f.text_field :phone_number -%>
  </div>
  
  <div class='field'>
    <%= f.label :company -%>
    <%= f.text_field :company -%>
  </div>
  
  <div class='field'>
    <%= f.label :gender -%>
    <%= f.text_field :gender -%>
  </div>
  
  <div class='field'>
    <%= f.label :website -%>
    <%= f.text_field :website -%>
  </div>
  
  <div class='field'>
    <%= f.label :latitude -%>
    <%= f.text_field :latitude -%>
  </div>
  
  <div class='field'>
    <%= f.label :longitude -%>
    <%= f.text_field :longitude -%>
  </div>
  
  <div class='field'>
    <%= f.label :email_opt_in -%>
    <%= f.check_box :email_opt_in -%>
  </div>
  
  <div class='field'>
    <%= f.label :newsletter_opt_in -%>
    <%= f.check_box :newsletter_opt_in -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.attendees.attendee'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @attendee.first_name)
              } %>
<% end -%>

app/views/admin/attendees/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @attendees.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'attendees' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/attendees/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'attendee', :collection => @attendees %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/attendees/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::AttendeesController.sortable? and Attendee.count > 1 %>